apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karsajobs-database

spec:
  serviceName: karsajobs-database
  replicas: 1
  selector:
    matchLabels:
      app: karsajob
  template:
    metadata:
      labels:
        app: karsajob
    spec:
      containers:
        - name: mongo
          image: mongo:latest 
          ports:
            - containerPort: 27017 
          env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db 
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
          readOnly: true
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
          readOnly: true

      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-config
        configMap:
          name: mongo-config
          items:
            - key: mongo.conf
              path: mongo.conf
      - name: mongo-secret
        secret:
          secretName: mongo-secret