apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual 
  hostPath:
    path: "/mnt/data/mongo"

---
# deklarasi konfigurasi untuk PVC

# gunakan api versi 1
apiVersion: v1

# tentukan jenis object = PersistentVolumeClaim
kind: PersistentVolumeClaim

# tambahkan metadata
metadata:
  # nama
  name: mongo-pv-claim
  # label
  labels:
    app: mongo

# tentukan spesifikasi
spec:
  storageClassName: manual
  # mode akses
  accessModes:
    - ReadWriteOnce
  # resources
  resources:
    requests:
      storage: 1Gi
